### PR TITLE
Rgparticipate

### PR DESCRIPTION
**Pull request by KatiRG**
Our blog post is in source/blog/teamblog.md. Qian is emailing the photo to Floor.

### CODE REVIEW

**Comment by sareg0** [comment]
amazing! Thanks @KatiRG we will review it tonight, and set it up for publish over the coming days.

**Comment by KatiRG** [comment]
Thanks @sareg0 ! We put in the picture link now and made some other edits, but now we're good for merge :)

**Comment by FloorD** [comment]
I like. @sareg0 you do the honors of merging?

**Comment by sareg0** [comment]
Hey there! Yay will do. The boat party post was posted today so will post tomorrow. So there is a quick breather.

**Comment by sareg0** [comment]
Dang, this image is quite long. We can only fit about 600px. Do you think you guys could resive @FloorD ... The alteration I make to the size via markdown doesn't seem to work :(

**Comment by KatiRG** [comment]
Hi all, I scaled the picture down by 60%--does this help?
Unfortunately I am going out of town until Tues so won't be able to fix it.
Can you do it @qianfinland?

**Comment by sareg0** [comment]
Hi there @KatiRG and @qianfinland, I can't see a new pull request, and the image via the link still seems to be the same size. Was it sent to @FloorD again?

**Comment by Qianfinland** [comment]
hi, i now send email to Floor for making the pic acceptable. My pair @KatiRG made the PR via her account, i guess i need to her back to update the PR. Or is there any suggestion that i can update the PR or you guys can do it when merge.

**Comment by sareg0** [comment]
Hi @Qianfinland that's fine, once the dimensions of the picture are changed, I will just updated the link in the original pull request, and send it live :)

**Comment by KatiRG** [comment]
Hi all,

Qian resized the picture here:
https://plus.google.com/photos?pid=6060047975426002370&oid=101906241547190058337
Let us know if it is ok.

Do you have anywhere to host it?

**Comment by sareg0** [comment]
@KatiRG not officially. Where was it hosted before?

**Comment by KatiRG** [comment]
@sareg0: @floordrees put it here for us:
http://www.1stfloorgraphics.nl/wp-content/uploads/teamparticipate.png

**Comment by sareg0** [comment]
@KatiRG it's okay, I just saved it to our assets file on the site. It's live now and the tweet with go out at 13:45 today. Thanks so much for doing the write up. I will close this one now.

**Pull request closed without merging**
