### PR TITLE
Turn sponsor plans into a more visible list, allows direct donations via Stripe forms

### PR DESCRIPTION
**Pull request by roidrage**
This is a work in progress, not ready for merging yet, but a basis for discussion.

This changes makes the plans more visible and a bit more distinctive:

It also adds the possibility of a direct donation via Stripe:

Needs an addition to support VAT as well, but that could be a smaller link below the "Become a Sponsor" link.

It's also missing the publishable Stripe token to be fully set up.

### CODE REVIEW

**Comment by roidrage** [comment]
Turned them into bigger button and added a form to donate custom amounts:

**Comment by svenfuchs** [comment]
Awesome, thanks @roidrage!

I'm afraid if we use Stripe checkout then we'd loose VAT from EU based sponsors. Gotta verify though. In that case I've got a halfbaked extract from the old love campaign code that we could hook up.

Anyway, this is fantastic!

**Comment by svenfuchs** [comment]
Hmmm, soo, after talking to @fritzek and @rkh a viable solution might be:
1. have a checkbox below the sponsor packages that, if you're from Germany, adds VAT to the amounts:

```
[x] We need to add VAT if your company is based in Germany OR 
     your company is based in the EU and you do not have a VAT ID.
```
1. collect the vat id from EU based companies later in the process.

**Comment by lislis** [comment]
Looks super awesome :dancer:

**Comment by svenfuchs** [comment]
Hmm, it seems that with Stripe checkout one still needs to have a backing app that actually collects the payment and does the error handling for that.

https://stripe.com/docs/checkout/guides/rails

In that case it might be simpler to just take the "old" approach ... I guess?

**Comment by roidrage** [comment]
The code to create a little Rails app is right there. Copy & paste it from the Stripe page, deploy a little Heroku app, boom, done.

**Comment by roidrage** [comment]
Above commit adds a toggle to enable/disable VAT.

**Comment by roidrage** [comment]
This tutorial has all the steps required to set up a Heroku app with Sinatra: https://stripe.com/docs/checkout/guides/sinatra

**Comment by roidrage** [comment]
Here's the full app, ready for copy & paste: https://gist.github.com/maccman/fd4887c35bb37964b6ff Even just needs the `post '/charge'` part and a proper thank you page. Or this repository could include a thank you page and the Sinatra app can redirect to it.

**Comment by svenfuchs** [comment]
we'll want to collect addtional info so we can list donors (pledgie style) and collect extra billing info (vat id at least) from companies

that gist is also lacking error handling

but yeah, i'll give that a try, too

**Comment by roidrage** [comment]
You can do that collection after the donation fact, even just manually, it'd be the same process as it is now with a manual bank transfer. Can always be automated once this is pushed out. The intent of this pull request is for now to make it easier for folks to donate money. The app handling the charges can be easily adapted to track any additional information later.

**Comment by roidrage** [comment]
I've checked the Stripe documentation a bit more and it seems that we need a little app either way, because the Stripe form itself doesn't allow tracking email addresses. So it could just be an extension to the example app that has an extra form asking for VAT ID, email address and anything else you need from donors. Submitting that form will then trigger the charge in Stripe.

**Comment by svenfuchs** [comment]
merging this now, gonna move it to a "hidden"/not-publicly-linked path and restore the old sponsors page for now though. then we can sort out the payment process on that hidden page.

**Pull request merged**
