### PR TITLE
Updated Campaign Page- including pagination of sponsors at bottom of screen

### PR DESCRIPTION
**Pull request by unicornzero**
Though I've not used gh-pages before, I am hoping to find ways to contribute to the amazing work your group is doing. I've made two adjustments to text and added a footer to the sponsors table so that pagination appears when someone scrolls to the bottom of the page, per the issue reported at https://github.com/rails-girls-summer-of-code/summer-of-code/issues/55

I'm brand new to using GitHub Pages, so I'm having difficulty generating a full preview on my local machine. Please let me know if any of this needs to be done differently. 

Thanks!
Rylee

### CODE REVIEW

**Comment by svenfuchs** [comment]
Hey @unicornzero, thanks for the pull request, this is awesome!

If you look at the page source now you see that the footer pagination is actually there, even though it seems it's still missing. I think the reason is that both paginations are positioned "absolute" in the containing `#thanks-folks` section. So they just both sit at the very same place at the top of the table.

I think it might work if we'd position both paginations separately like so:

```
.pagination {
  position: absolute;
  right: 0px;
}
thead .pagination {
  top: 67px;
}
```

... or something :)

Would you want to look into this?

**Comment by unicornzero** [comment]
@svenfuchs 

I'll be happy to work on this today. Thank you for pointing that out!

-Rylee

**Comment by unicornzero** [comment]
@svenfuchs & @lislis 
I got jekyll working on my local machine and am now able to render most components of the SOC site locally. I'm having difficulty seeing the donations listed in my local version of the campaign page. Is there a way I could configure this to preview properly locally?

**Comment by PallaviTS** [comment]
Even I had the same problem . Couldn't see the list on my machine .
Clicking on see less seems to do nothing .

On Tue, Jun 25, 2013 at 9:32 PM, unicornzero notifications@github.comwrote:

> @svenfuchs https://github.com/svenfuchs & @lislishttps://github.com/lislis
> I got jekyll working on my local machine and am now able to render most
> components of the SOC site locally. I'm having difficulty seeing the
> donations listed in my local version of the campaign page. Is there a way I
> could configure this to preview properly locally?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rails-girls-summer-of-code/summer-of-code/pull/80#issuecomment-19987071
> .

## 

Regards ,
Pallavi TS

**Comment by svenfuchs** [comment]
@unicornzero @PallaviTS 

hmmm, i see ... well you could install the campaign app, too, and add some data.

but maybe it's easier to just change this line:

https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/js/donations.js#L3

```
var ENV = 'production'
```

that should then always load donation data from the real app. does that work for you?

**Comment by unicornzero** [comment]
Ah! That did work once I restarted the jekyll server... Thank you!!!

Back at it...

**Comment by PallaviTS** [comment]
Changing it just production din't help .

On Tue, Jun 25, 2013 at 9:44 PM, Sven Fuchs notifications@github.comwrote:

> @unicornzero https://github.com/unicornzero @PallaviTShttps://github.com/PallaviTS
> 
> hmmm, i see ... well you could install the campaign app, too, and add some
> data.
> 
> but maybe it's easier to just change this line:
> 
> https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/js/donations.js#L3
> 
> var ENV = 'production'
> 
> that should then always load donation data from the real app. does that
> work for you?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rails-girls-summer-of-code/summer-of-code/pull/80#issuecomment-19987858
> .

## 

Regards ,
Pallavi TS

**Comment by PallaviTS** [comment]
Yay! Got it :) Thank you Sven :)

On Tue, Jun 25, 2013 at 9:56 PM, Pallavi Shastry pallavi046@gmail.comwrote:

> Changing it just production din't help .
> 
> On Tue, Jun 25, 2013 at 9:44 PM, Sven Fuchs notifications@github.comwrote:
> 
> > @unicornzero https://github.com/unicornzero @PallaviTShttps://github.com/PallaviTS
> > 
> > hmmm, i see ... well you could install the campaign app, too, and add
> > some data.
> > 
> > but maybe it's easier to just change this line:
> > 
> > https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/js/donations.js#L3
> > 
> > var ENV = 'production'
> > 
> > that should then always load donation data from the real app. does that
> > work for you?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/rails-girls-summer-of-code/summer-of-code/pull/80#issuecomment-19987858
> > .
> 
> ## 
> 
> Regards ,
> Pallavi TS

## 

Regards ,
Pallavi TS

**Comment by unicornzero** [comment]
Cool. Looks like your css suggestion worked, @svenfuchs. I'll polish up the commit and send it over. :+1:

**Comment by svenfuchs** [comment]
Awesome, @unicornzero! Seems to work.

There's still something odd, when I click one of the links at the bottom then it sometimes jumps to the footer somehow.

Maybe we need to cancel the click event or prevent the default action?

**Comment by unicornzero** [comment]
Whew. Okay, I do see the issue, and after staring at the js and jquery for quite a while, I'm no closer to figuring out how to fix it.

I know very little about jquery, and couldn't determine the mechanism behind the page moving when we click the pagination links. Was the pagination custom coded for this app, or is it from a library I could reference? Is the person who wrote it available?

I'd like to figure it out, but I'm pretty far outside of my current knowledge base. If someone else wants to grab it, that's fine by me.

-Rylee

**Comment by PallaviTS** [comment]
Pallavi shastry sent you an invitation

Twitter helps you stay connected with what's happening right now and with the people and organizations you care about.

  Accept invitation

https://twitter.com/i/d93eb550-2c67-4e32-a28c-62057358e788

---

This message was sent by Twitter on behalf of Twitter users who entered your email address to invite you to Twitter.
Unsubscribe: https://twitter.com/i/o?t=1&iid=f1d2ceef-5d75-438b-884d-b022810bdd80&uid=0&c=IuVwbCB3dgG5nKRXri1sJ%2Fc%2Fed9fw5TuWui6KYICp9aJK2F%2BPXUmUGkOASh8BD1s8cwOK2ofBvM7guxBD1%2Fhy4G%2BUSqNC8tZMtp2Cad5XBTh%2FkdFeS9z5A%3D%3D&nid=9+26

Need help?
https://support.twitter.com

**Pull request merged**
