### PR TITLE
fixes broken link

### PR DESCRIPTION
**Pull request by shaunagm**
The home page currently links to the (non-existent) http://railsgirlssummerofcode.org/application instead of http://railsgirlssummerofcode.org/application-guide/.

### CODE REVIEW

**Comment by carpodaster** [comment]
Awesome, thanks for spotting (and fixing) this!

**Comment by anikalindtner** [comment]
yay! thanks @shaunagm <3

**Comment by sareg0** [comment]
Yes, thanks @shaunagm, I didn't even think about that one.

**Comment by shaunagm** [comment]
You're welcome!  Found it while researching for [this](http://openhatch.org/blog/2014/summer-internships-for-open-source-enthusiasts/).

**Pull request merged**
