### PR TITLE
add companies blog post

### PR DESCRIPTION
**Pull request by svenfuchs**
Is this a good title? What's a better one?

Other things to be done:
- [x] add the email address, which one do we use? summer-of-code@gmail.org?
- [x] add the date for the campaign start
- [x] link to relevant external pages, e.g. Travis Foundation
- [x] link to the coaching companies page, if available, yet (we should try!)

### CODE REVIEW

**Comment by sareg0** [comment]
## Title Ideas

"Rails Girls Summer of Code Needs You!"
"3 Ways Your Company Can Get Involved in Open Source"
"3 Ways Your Company Can Get Involved with Summer of Code" 
"3 Ways You Can Support Rails Girls Summer of Code 2014"
"How To Sponsor Rails Girls Summer of Code"
"Sponsor Rails Girls Summer of Code in 2014"

**Comment by FloorD** [comment]
How your company can support diversity in Open Source

**Comment by anikalindtner** [comment]
3 Ways your company can support diversity in Open Source

or any other of the "3 ways" would be nice

**Comment by svenfuchs** [comment]
went with "3 Ways Your Company Can Support Rails Girls Summer of Code 2014" for now

**Comment by anikalindtner** [comment]
sounds good!

**Pull request merged**
