### PR TITLE
Use asset pipeline + SASS & Compass + minifiers

### PR DESCRIPTION
**Pull request by josepjaume**
Hi again!

This is kind of a restructuring of the current website using an asset pipeline so your CSS and JS gets automatically minified & merged into a single file.

Note that you will have to install the gems required to make this work:

```
bundle install
```

And develop watching the files to change:

```
jekyll serve --watch
```

I've used some compass helpers to auto-prefix things like `box-shadow`, `text-shadow` and such.

Hope you like it!

(it looks huge but it's just because it comes with the compiled files!)

### CODE REVIEW

**Comment by josepjaume** [comment]
Related to #21

**Comment by josepjaume** [comment]
Hey, don't merge this! Seems like Jekyll on github is complaining. Let's see..

**Comment by josepjaume** [comment]
Oh man... It seems like this isn't gonna work with github pages at all :(

**Comment by lislis** [comment]
Just asset pipelines or the whole sass thing? I was looking forward to it :/

**Comment by josepjaume** [comment]
Actually, the thing is that github doesn't support plugins outside a certain set, so neither sass or the asset pipeline are supported

:( https://help.github.com/articles/pages-don-t-build-unable-to-run-jekyll

Jekyll is really limited either way. I would switch to Middleman that's actually a full-featured rack app. You can deploy it free on heroku:

http://middlemanapp.com/

If you're open to using Heroku, I can build the app myself :). I just hate leaving things in the middle!

**Comment by svenfuchs** [comment]
Why not just pre-compile the assets?

$ sass --watch foo.sass:foo.css

Github pages are just handy because of auto deployment etc.

**Comment by josepjaume** [comment]
Oh, right, so silly of me. I'll update the PR tomorrow!

It's a pity we'll be missing the rest of the pipeline though :)

**Comment by lislis** [comment]
Thanks @josepjaume for the enthusiasm :D

**Pull request closed without merging**
