### PR TITLE
Add blog post by Rapid Rails Girls

### PR DESCRIPTION
**Pull request by kat-crumbs**
We hope the usage of emojis is ok

### CODE REVIEW

**Comment by anikalindtner** [comment]
the usage of emojis is highly recommended ;) awesome post!

**Comment by kat-crumbs** [comment]
Glad you like it :)

**Comment by anikalindtner** [comment]
yeah, i'm gonna merge it! wheee!

**Comment by anikalindtner** [comment]
@kat-crumbs this one line keeps looking weird:
screen shot 2014-08-22 at 13 45 32

funnily enough, only when you view it from /blog. if you go directly to the article, it disappears. also your name isn't displayed. 

screen shot 2014-08-22 at 13 47 55

usually this means there is somewhere a tiny markdown mistake.. can you have a looksie? maybe even ping your coach, if you don't find anything?

**Comment by kat-crumbs** [comment]
@anikalindtner we found the bug, but how can we change it?! Also we'll delete the emojis, as they obviously can't be displayed in the blog

**Comment by anikalindtner** [comment]
@kat-crumbs you can just send a new pull request, i'd say. or is that too complicated?

**Comment by kat-crumbs** [comment]
@anikalindtner ok, have a look at https://github.com/rails-girls-summer-of-code/summer-of-code/pull/244 
... there are merge conflicts though...

**Pull request merged**
