### PR TITLE
Create 2014-09-19-introducing-team-mutants.md

### PR DESCRIPTION
**Pull request by AkshataDM**
Hope this is good! :)

### CODE REVIEW

**Comment by berlintam** [comment]
woot woot! Mutants, you're awesome! :+1: :smile: 

@sareg0 @anikalindtner is this good to go?

**Comment by berlintam** [comment]
thanks @sareg0 :)

**Comment by sareg0** [comment]
Sorry for the delay guys @berlintam the picture does not seem to be working. The link is with https; does this make a difference to the picture displaying. Perhaps it could be emailed to me directly, or the image could be hosted somewhere else?

**Comment by sareg0** [comment]
@AkshataDM could you look into sending me the picture directly (regan.sara@gmail.com), or hosted it somewhere else

**Comment by berlintam** [comment]
@sareg0 i just sent you a pic!

**Comment by sareg0** [comment]
nice; fixed.

**Pull request merged**
