### PR TITLE
Middleman setup

### PR DESCRIPTION
**Pull request by lislis**
!!!Caution!!!
The new setup with middleman. This is a complete rewrite of the current page. Please take some time and take a look if something is misssing or broken. 
Also, aside from "summer of code will happen again' post, I didn't port any of the old blogposts.

### CODE REVIEW

**Comment by sareg0** [comment]
Hey, 
I installed middleman, and looked at the branch locally, and everything seems to be in order, nothing broken. I don't really know what the next step is on this... Someone now deploys?

I just have a few questions
1. Should we port over the rest of the blog posts, before deploying the new setup? 
2. Should I hold of on all other changes I intend to make until this branch is merged to the main site?

Any insight from our devsperts very welcome ;)

The new middleman setup seems to look quite nice though, and very pleasing to the eye.

**Comment by anikalindtner** [comment]
@svenfuchs maybe?

**Comment by sareg0** [comment]
Locally the version worked, but when we merged to live, we got a 404... We are now going back to the drawing board to figure out why. Help welcome.

**Comment by lislis** [comment]
hey, sry for not being available. 
Something that I should have written down somewhere (stupid me) is that this branch needs to be merged into master. from there you run $ middleman deploy which then populates the gh-pages branch. 
But now that there are so many new changes, I'm wondering if it makes senses at all to invest more time in this?

**Comment by svenfuchs** [comment]
Hey @lislis this is pity. I guess the timing (change the tech in the middle of the first big wave of changing contents) wasn't quite perfect, and I haven't thought about that either.

We've had deploying figured out, but then we found issues with the CSS on bigger screens, and weren't sure how to fix it. Thus we've decided we had to roll back to the previous version.

**Comment by lislis** [comment]
Don't worry :) I'll see what I can do on the current site

**Pull request merged**
