### PR TITLE
Create Team Species+ says hello

### PR DESCRIPTION
**Pull request by morvenn**
Species+ blog post :)

### CODE REVIEW

**Comment by morvenn** [comment]
Done! ;-)

**Comment by alicetragedy** [comment]
awesome :heart: 
it will be posted tomorrow!

**Comment by anikalindtner** [comment]
hej girls! looks like this isn't a markdown file. ... or is it? could you have a look at the other blog post and do it in the same format? thanks so much! https://raw.githubusercontent.com/rails-girls-summer-of-code/summer-of-code/gh-pages/blog/_posts/2014-07-31-introduction-about-aria-team.md

**Comment by anikalindtner** [comment]
also could you insert a photo of you both or even better of your whole team? can be something silly or funny or just a nice friday-hug picture... thank you <3

**Pull request merged**
