### PR TITLE
Link RGSoC projects

### PR DESCRIPTION
**Pull request by carpodaster**
Adds links to the canonical websites of the listed projects. That is: where I could find one within a 30secs search timeframe. If anyone can point me to the missing ones, I'll gladly add those, too.

### CODE REVIEW

**Comment by anikalindtner** [comment]
@carpodaster i've purpously not linked the projects, since i don't want it to be a link cemetary (too many links in a blog post don't look good), but instead linked to the teams-site, so that no team will feel excluded.

**Comment by carpodaster** [comment]
@anikalindtner Allright. I know where you're coming from. Gonna close this then.

**Comment by anikalindtner** [comment]
thank you nevertheless for your effort. <3<3<3 (and this so late in the eve :D )

**Comment by anikalindtner** [comment]
btw. this is not true...

screen shot 2014-10-06 at 20 47 33

weird.

**Comment by carpodaster** [comment]
That's your Ghost in the Shell!

**Pull request closed without merging**
