### PR TITLE
Home

### PR DESCRIPTION
**Pull request by katrin-k**
Update home page: video and last year's sponsors out, see issue #143

Double-check welcome. Reduced it to the most necessary and clean all from last year.

### CODE REVIEW

**Comment by svenfuchs** [comment]
looks good to me! let's get this merged, shall we?

**Comment by katrin-k** [comment]
sweet :)

**Comment by svenfuchs** [comment]
It seems this has removed the big header photo http://railsgirlssummerofcode.org/

Can we bring that back?

**Comment by katrin-k** [comment]
uuh. will do.

**Comment by katrin-k** [comment]
darn. ds_store trouble again and no arne around to help. 
@svenfuchs can you please insert 

```
<div class="keyvisual"></div> 
```

in line 7 of index.html. all css settings should be fine.

**Comment by svenfuchs** [comment]
cool, i've merged the pull request by now :)

**Pull request merged**
