### PR TITLE
Create 2014-08-22-rgsoc-day-off.md

### PR DESCRIPTION
**Pull request by alicetragedy**
@anikalindtner feedback would be great! not sure about the permalink either (should I add the date?) so feel free to make changes before we can merge. thank you! :heart:

### CODE REVIEW

**Comment by anikalindtner** [comment]
@alicetragedy i love love love the post! i edited some parts and added a gif. feel free to change it all back or edit or whatever. :)

**Comment by alicetragedy** [comment]
I think it's great like that, good changes :thumbsup: 
but maybe we should change the date and publish it tomorrow so there's no blog post overload today - or does that not really matter?

**Comment by anikalindtner** [comment]
I don't think it matters. we can tweet the hell out of it tomorrow, but still publish it today, so we can reference it in the email to the students.

**Comment by alicetragedy** [comment]
:+1: want to have the honour to merge? ;)

**Comment by anikalindtner** [comment]
MERGED! \o/

**Comment by alicetragedy** [comment]
:tada:

**Pull request merged**
