### PR TITLE
Fix pagination on campaign page

### PR DESCRIPTION
**Pull request by bastilian**
Fixes the issues mentioned in slack the pagination looks like it should now:
screen shot 2014-04-04 at 15 10 39

### CODE REVIEW

**Comment by svenfuchs** [comment]
@bastilian hey, thanks for looking into this. it's quite curious why this broke.

the intended behaviour would be the one that you can see on http://2013.railsgirlssummerofcode.org/campaign (the donations.json sometimes takes like ~30 sec to load since heroku spins down the app there). I.e.:

image

I guess we could still merge your changes, to have it fixed quickly. But I'd also like the intended behaviour to be restored. I can look into that if you like.

**Comment by bastilian** [comment]
updated the css and reverted the removal of the spans. now it works like it really should. :)
screen shot 2014-04-04 at 16 37 32

**Comment by svenfuchs** [comment]
@bastilian awesome! let's get this merged.

**Comment by anikalindtner** [comment]
yay @bastilian! <3

**Pull request merged**
