### PR TITLE
Update 2014-08-22-blog-post-self-promotion-by-RapidRailsGirls.md

### PR DESCRIPTION
**Pull request by svenfuchs**
Rebase https://github.com/rails-girls-summer-of-code/summer-of-code/pull/244

### CODE REVIEW

**Comment by kat-crumbs** [comment]
@svenfuchs and @anikalindtner it seems like the deletions we made in line 27 were not successful. Could you maybe just delete everything in the brackets , like all the symbols

**Comment by anikalindtner** [comment]
hej @kat-crumbs i've deleted the symbols and put your twitter handle in. now everything should be looking good :)

**Comment by kat-crumbs** [comment]
thanks a bunch @anikalindtner ! :+1:

**Comment by sferik** [comment]
:frowning: I liked it better with :heart_eyes: and :sparkles: :exclamation:

**Comment by sferik** [comment]
Maybe the @RapidRailsGirls team can add emoji support to the Summer of Code blog? GitHub recently open-sourced [`gemoji`](https://github.com/github/gemoji) a Ruby gem that adds emoji support to Rails apps.

**Comment by alicetragedy** [comment]
the best ideas always involve emojis. :sparkles:

**Pull request merged**
